In [2]:
from pathlib import Path
import pandas as pd

RAW_DIR = Path("../data/raw")

files = sorted(RAW_DIR.rglob("*.csv"))

for file in files:
    print(file.name)

서울특별시_전월세가_2023.csv
서울특별시_전월세가_2024.csv
서울특별시_전월세가_2025.csv

In [3]:
file_2023 = files[0]

df_sample = pd.read_csv(
    file_2023,
    nrows=5
)

df_sample

,접수년도,자치구코드,자치구명,법정동코드,법정동명,지번구분코드,지번구분,본번,부번,층,...,보증금(만원),임대료(만원),건물명,건축년도,건물용도,계약기간,신규계약구분,갱신청구권사용,종전보증금,종전임대료
0,2023,11440,마포구,11000,노고산동,1,대지,1,1,8,...,10000,40,\t(1-1)\t,1998,오피스텔,23.01~24.01,신규,NaN,0.0,0.0
1,2023,11440,마포구,11000,노고산동,1,대지,1,1,5,...,10000,55,\t(1-1)\t,1998,오피스텔,23.02~24.02,갱신,NaN,10000.0,55.0
2,2023,11440,마포구,11000,노고산동,1,대지,1,1,9,...,21000,0,\t(1-1)\t,1998,오피스텔,23.02~24.02,신규,NaN,0.0,NaN
3,2023,11170,용산구,11300,원효로2가,1,대지,1,0,9,...,23900,0,\t(1)\t,1990,오피스텔,23.09~25.09,신규,NaN,0.0,NaN
4,2023,11440,마포구,11000,노고산동,1,대지,1,1,9,...,22000,0,\t(1-1)\t,1998,오피스텔,NaN,NaN,NaN,NaN,NaN

In [4]:
df_sample.columns.tolist()

['접수년도',
 '자치구코드',
 '자치구명',
 '법정동코드',
 '법정동명',
 '지번구분코드',
 '지번구분',
 '본번',
 '부번',
 '층',
 '계약일',
 '전월세구분',
 '임대면적',
 '보증금(만원)',
 '임대료(만원)',
 '건물명',
 '건축년도',
 '건물용도',
 '계약기간',
 '신규계약구분',
 '갱신청구권사용',
 '종전보증금',
 '종전임대료']

In [5]:
len(df_sample.columns)

23

In [6]:
use_cols = [
    "접수년도",
    "자치구명",
    "법정동명",
    "층",
    "계약일",
    "전월세구분",
    "임대면적",
    "보증금(만원)",
    "임대료(만원)",
    "건물명",
    "건축년도",
    "건물용도",
    "계약기간",
    "신규계약구분",
]

df_2023 = pd.read_csv(
    file_2023,
    usecols=use_cols
)

df_2023.shape

(545813, 14)

In [7]:
df_2023["건물용도"].value_counts(dropna=False)

건물용도
아파트      233849
단독다가구    133456
연립다세대    116141
오피스텔      62367
Name: count, dtype: int64

In [8]:
df_2023["전월세구분"].value_counts(dropna=False)

전월세구분
월세    283341
전세    262472
Name: count, dtype: int64

In [9]:
df_2023["신규계약구분"].value_counts(dropna=False)

신규계약구분
신규     348168
갱신     106947
NaN     90698
Name: count, dtype: int64

In [10]:
df_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 545813 entries, 0 to 545812
Data columns (total 14 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   접수년도     545813 non-null  int64
 1   자치구명     545813 non-null  str
 2   법정동명     545813 non-null  str
 3   층        412357 non-null  float64
 4   계약일      545813 non-null  int64
 5   전월세구분    545813 non-null  str
 6   임대면적     545813 non-null  float64
 7   보증금(만원)  545813 non-null  int64
 8   임대료(만원)  545813 non-null  int64
 9   건물명      412357 non-null  str
 10  건축년도     536316 non-null  float64
 11  건물용도     545813 non-null  str
 12  계약기간     440065 non-null  str
 13  신규계약구분   455115 non-null  str
dtypes: float64(3), int64(4), str(7)
memory usage: 58.3 MB

In [11]:
df_apt_2023 = df_2023[
    df_2023["건물용도"] == "아파트"
].copy()

df_apt_2023.shape

(233849, 14)

In [12]:
df_apt_2023["전월세구분"].value_counts()

전월세구분
전세    139307
월세     94542
Name: count, dtype: int64

In [13]:
df_apt_2023["신규계약구분"].value_counts(dropna=False)

신규계약구분
신규     138033
갱신      61098
NaN     34718
Name: count, dtype: int64

In [14]:
df_apt_2023.isnull().sum().sort_values(ascending=False)

계약기간       51754
신규계약구분     34718
건축년도          47
법정동명           0
접수년도           0
자치구명           0
전월세구분          0
계약일            0
층              0
임대면적           0
건물명            0
임대료(만원)        0
보증금(만원)        0
건물용도           0
dtype: int64

In [15]:
df_apt_2023[
    [
        "층",
        "임대면적",
        "보증금(만원)",
        "임대료(만원)",
        "건축년도"
    ]
].describe()

,층,임대면적,보증금(만원),임대료(만원),건축년도
count,233849.000000,233849.000000,233849.000000,233849.000000,233802.000000
mean,9.520237,69.326181,38769.417932,40.962647,2004.467391
std,6.431148,28.653112,33200.254757,87.392642,12.450993
min,-2.000000,10.320000,0.000000,0.000000,1961.000000
25%,5.000000,51.120000,13347.000000,0.000000,1995.000000
50%,8.000000,59.990000,34000.000000,0.000000,2005.000000
75%,13.000000,84.920000,55000.000000,53.000000,2016.000000
max,69.000000,314.800000,740000.000000,4500.000000,2024.000000

In [16]:
df_apt_2023.dtypes

접수년도         int64
자치구명           str
법정동명           str
층          float64
계약일          int64
전월세구분          str
임대면적       float64
보증금(만원)      int64
임대료(만원)      int64
건물명            str
건축년도       float64
건물용도           str
계약기간           str
신규계약구분         str
dtype: object

In [17]:
df_apt_2023[
    [
        "층",
        "임대면적",
        "보증금(만원)",
        "임대료(만원)",
        "건축년도"
    ]
].describe()

,층,임대면적,보증금(만원),임대료(만원),건축년도
count,233849.000000,233849.000000,233849.000000,233849.000000,233802.000000
mean,9.520237,69.326181,38769.417932,40.962647,2004.467391
std,6.431148,28.653112,33200.254757,87.392642,12.450993
min,-2.000000,10.320000,0.000000,0.000000,1961.000000
25%,5.000000,51.120000,13347.000000,0.000000,1995.000000
50%,8.000000,59.990000,34000.000000,0.000000,2005.000000
75%,13.000000,84.920000,55000.000000,53.000000,2016.000000
max,69.000000,314.800000,740000.000000,4500.000000,2024.000000

In [18]:
print("면적 0 이하:",
      (df_apt_2023["임대면적"] <= 0).sum())

print("보증금 0 미만:",
      (df_apt_2023["보증금(만원)"] < 0).sum())

print("임대료 0 미만:",
      (df_apt_2023["임대료(만원)"] < 0).sum())

print("층 0 이하:",
      (df_apt_2023["층"] <= 0).sum())

print("건축년도 1900 미만:",
      (df_apt_2023["건축년도"] < 1900).sum())

면적 0 이하: 0
보증금 0 미만: 0
임대료 0 미만: 0
층 0 이하: 23
건축년도 1900 미만: 0

In [19]:
df_apt_2023.duplicated().sum()

np.int64(103)

In [20]:
print(
    "전세인데 월세가 0이 아닌 건수:",
    (
        (df_apt_2023["전월세구분"] == "전세")
        & (df_apt_2023["임대료(만원)"] != 0)
    ).sum()
)

print(
    "월세인데 월세가 0인 건수:",
    (
        (df_apt_2023["전월세구분"] == "월세")
        & (df_apt_2023["임대료(만원)"] == 0)
    ).sum()
)

전세인데 월세가 0이 아닌 건수: 0
월세인데 월세가 0인 건수: 35

In [22]:
cols_check = [
    "자치구명",
    "법정동명",
    "건물명",
    "전월세구분",
    "임대면적",
    "층",
    "보증금(만원)",
    "임대료(만원)",
    "건축년도",
    "신규계약구분"
]

In [23]:

df_apt_2023[cols_check].sort_values(
    "보증금(만원)",
    ascending=False
).head(10)

,자치구명,법정동명,건물명,전월세구분,임대면적,층,보증금(만원),임대료(만원),건축년도,신규계약구분
93302,용산구,한남동,나인원한남,전세,244.35,2.0,740000,0,2019.0,신규
229758,용산구,한남동,나인원한남,전세,206.90,6.0,700000,0,2019.0,신규
2377,용산구,한남동,나인원한남,전세,206.90,2.0,670000,0,2019.0,신규
330099,용산구,한남동,나인원한남,전세,244.35,3.0,661500,0,2019.0,갱신
211901,용산구,한남동,나인원한남,전세,206.90,3.0,600000,0,2019.0,신규
51186,성동구,성수동1가,갤러리아포레,전세,218.58,38.0,590000,0,2011.0,신규
208823,강남구,청담동,상지리츠빌카일룸3차,전세,254.96,9.0,580000,0,2009.0,신규
34958,용산구,한남동,나인원한남,전세,206.90,9.0,577000,0,2019.0,신규
217449,강남구,청담동,PH129,전세,273.96,2.0,570000,0,2020.0,갱신
162165,용산구,한남동,한남더힐,월세,235.31,5.0,560000,42,2011.0,갱신

In [24]:

df_apt_2023[cols_check].sort_values(
    "임대료(만원)",
    ascending=False
).head(10)

,자치구명,법정동명,건물명,전월세구분,임대면적,층,보증금(만원),임대료(만원),건축년도,신규계약구분
384462,성동구,성수동1가,아크로서울포레스트,월세,264.55,47.0,200000,4500,2020.0,NaN
195525,성동구,성수동1가,아크로서울포레스트,월세,159.60,32.0,50000,2800,2020.0,신규
194087,성동구,성수동1가,아크로서울포레스트,월세,159.60,25.0,100000,2600,2020.0,신규
297817,성동구,성수동1가,아크로서울포레스트,월세,273.93,47.0,400000,2500,2020.0,신규
27870,용산구,한남동,나인원한남,월세,206.90,7.0,200000,2500,2019.0,신규
344469,용산구,한남동,한남더힐,월세,233.06,4.0,20000,2500,2011.0,신규
430371,용산구,한남동,한남더힐,월세,233.06,4.0,30000,2500,2011.0,신규
146633,강남구,청담동,상지카일룸,월세,244.46,4.0,30000,2500,2003.0,신규
297820,성동구,성수동1가,아크로서울포레스트,월세,273.93,47.0,400000,2500,2020.0,NaN
189938,용산구,한남동,한남더힐,월세,235.31,2.0,30000,2500,2011.0,신규

In [25]:

df_apt_2023[
    (df_apt_2023["전월세구분"] == "월세")
    & (df_apt_2023["임대료(만원)"] == 0)
][cols_check]

,자치구명,법정동명,건물명,전월세구분,임대면적,층,보증금(만원),임대료(만원),건축년도,신규계약구분
20829,양천구,목동,목동신시가지4,월세,65.34,13.0,47250,0,1986.0,NaN
51922,중랑구,면목동,봄작시티201,월세,16.66,11.0,19100,0,2022.0,신규
93105,서초구,서초동,서초롯데캐슬프레지던트,월세,84.97,9.0,70000,0,2014.0,신규
106776,성북구,길음동,길음뉴타운3단지푸르지오,월세,84.97,15.0,20000,0,2005.0,NaN
111203,금천구,독산동,금천롯데캐슬골드파크3차,월세,84.41,30.0,57000,0,2018.0,신규
136839,은평구,응암동,백련산힐스테이트2차,월세,84.59,2.0,36750,0,2011.0,갱신
140779,구로구,천왕동,천왕이펜하우스7단지,월세,29.96,5.0,5029,0,2017.0,NaN
179750,마포구,용강동,래미안마포리버웰,월세,84.97,2.0,78000,0,2015.0,신규
202499,강서구,마곡동,마곡13단지힐스테이트마스터,월세,59.98,4.0,20000,0,2017.0,신규
216735,구로구,천왕동,천왕이펜하우스7단지,월세,29.96,4.0,5029,0,2017.0,NaN
216736,구로구,천왕동,천왕이펜하우스7단지,월세,29.96,8.0,5029,0,2017.0,NaN
216741,구로구,천왕동,천왕이펜하우스7단지,월세,29.96,5.0,5029,0,2017.0,NaN
219008,영등포구,신길동,준타워,월세,15.54,8.0,15200,0,2023.0,갱신
219748,양천구,목동,목동신시가지1,월세,154.44,5.0,100000,0,1985.0,갱신
230419,구로구,항동,하버라인2단지,월세,59.86,16.0,20000,0,2019.0,신규
236039,강서구,마곡동,마곡엠밸리9단지,월세,59.86,8.0,10000,0,2021.0,신규
238281,강남구,삼성동,삼성동한솔아파트,월세,109.51,17.0,80000,0,1998.0,신규
242087,마포구,공덕동,래미안공덕5차,월세,59.97,5.0,20000,0,2011.0,신규
252304,구로구,항동,하버라인2단지,월세,59.86,6.0,25000,0,2019.0,신규
275930,중구,만리동2가,서울역센트럴자이,월세,59.94,14.0,60197,0,2017.0,갱신
300680,서초구,서초동,신구블레스벨리,월세,152.48,1.0,90000,0,2002.0,신규
303109,양천구,목동,목동신시가지6,월세,95.03,11.0,80000,0,1986.0,NaN
315161,노원구,상계동,상계주공2(고층),월세,32.39,10.0,13150,0,1987.0,NaN
325660,영등포구,영등포동4가,영등포그랑그루,월세,12.10,7.0,13000,0,2012.0,갱신
337625,노원구,월계동,현대,월세,114.99,24.0,38000,0,2000.0,신규
345855,강남구,논현동,논현베르빌,월세,132.59,1.0,78000,0,2002.0,갱신
349854,영등포구,신길동,준타워,월세,15.54,7.0,15200,0,2023.0,갱신
405322,마포구,신수동,대원칸타빌,월세,117.18,3.0,80000,0,2004.0,신규
437619,강서구,등촌동,주공3,월세,58.14,4.0,35000,0,1995.0,NaN
439589,송파구,장지동,위례중앙푸르지오1단지,월세,110.22,18.0,95000,0,2016.0,신규
464574,동대문구,답십리동,청계한신휴플러스,월세,84.73,21.0,55300,0,2010.0,NaN
464575,동대문구,답십리동,청계한신휴플러스,월세,84.73,21.0,55300,0,2010.0,갱신
466640,동작구,상도동,건영,월세,32.80,14.0,2503,0,1997.0,NaN
497253,서초구,반포동,반포래미안아이파크,월세,59.95,17.0,90000,0,2018.0,신규
509239,강동구,암사동,한솔솔파크,월세,84.98,14.0,67000,0,2009.0,신규

In [26]:

df_apt_2023[
    df_apt_2023["층"] <= 0
][cols_check]

,자치구명,법정동명,건물명,전월세구분,임대면적,층,보증금(만원),임대료(만원),건축년도,신규계약구분
5727,용산구,이촌동,강변,월세,66.08,-1.0,3500,45,1971.0,신규
27414,용산구,이촌동,강변,전세,58.58,-1.0,13000,0,1971.0,NaN
39034,용산구,이촌동,강변,월세,63.93,-1.0,3000,70,1971.0,신규
69293,성동구,옥수동,옥수파크힐스101동~116동,전세,76.66,-1.0,90000,0,2016.0,NaN
101249,금천구,시흥동,대도훼미리,월세,57.69,-1.0,200,10,1991.0,NaN
129130,은평구,진관동,우물골2단지두산위브(223~244동)BL2-7,월세,101.49,-2.0,40000,40,2010.0,신규
179424,중구,만리동2가,서울역센트럴자이,월세,39.95,-1.0,1388,19,2017.0,NaN
198265,중구,신당동,다다아파트,전세,59.95,-1.0,12000,0,2000.0,신규
237695,성동구,옥수동,옥수파크힐스101동~116동,월세,76.66,-1.0,30000,290,2016.0,신규
243042,종로구,명륜1가,방산(5-102),월세,25.29,-2.0,9000,30,1995.0,신규
278445,성동구,옥수동,옥수파크힐스101동~116동,월세,76.66,-2.0,20000,330,2016.0,NaN
278446,성동구,옥수동,옥수파크힐스101동~116동,월세,76.66,-2.0,20000,330,2016.0,신규
289783,중구,신당동,우석,전세,59.99,-1.0,13000,0,2001.0,NaN
380950,서대문구,홍제동,홍제역해링턴플레이스,월세,67.24,-2.0,2000,210,2021.0,신규
405984,서대문구,홍제동,홍제역해링턴플레이스,월세,59.99,-1.0,5000,200,2021.0,신규
409577,용산구,원효로1가,로얄카운티-3,전세,130.93,-1.0,65000,0,2007.0,신규
412534,용산구,이촌동,로얄맨숀,월세,85.95,-1.0,4000,210,1972.0,신규
458521,중구,신당동,유정,전세,29.40,-1.0,6500,0,2001.0,신규
478114,은평구,진관동,우물골2단지두산위브(223~244동)BL2-7,전세,134.51,-2.0,75000,0,2010.0,신규
483132,용산구,이촌동,강변,월세,63.93,-1.0,2000,55,1971.0,신규
488225,용산구,동빙고동,노블캐슬,월세,165.76,-1.0,6000,500,2008.0,신규
539188,성북구,장위동,신장위아파트,전세,80.55,-1.0,13000,0,2003.0,신규
541870,은평구,진관동,우물골2단지두산위브(223~244동)BL2-7,월세,134.71,-2.0,61000,35,2010.0,갱신

In [27]:

duplicates = df_apt_2023[
    df_apt_2023.duplicated(keep=False)
].sort_values(
    ["자치구명", "법정동명", "건물명", "계약일"]
)

duplicates.head(20)

,접수년도,자치구명,법정동명,층,계약일,전월세구분,임대면적,보증금(만원),임대료(만원),건물명,건축년도,건물용도,계약기간,신규계약구분
278524,2023,강남구,개포동,5.0,20230720,전세,39.53,37500,0,성원대치2단지아파트,1992.0,아파트,23.09~25.09,갱신
278526,2023,강남구,개포동,5.0,20230720,전세,39.53,37500,0,성원대치2단지아파트,1992.0,아파트,23.09~25.09,갱신
7859,2023,강남구,논현동,10.0,20230222,전세,84.99,85000,0,e-편한세상,2005.0,아파트,23.03~25.03,갱신
7863,2023,강남구,논현동,10.0,20230222,전세,84.99,85000,0,e-편한세상,2005.0,아파트,23.03~25.03,갱신
99696,2023,강남구,대치동,14.0,20230224,전세,128.03,100000,0,"쌍용대치아파트1동,2동,3동,5동,6동",1983.0,아파트,23.02~25.02,갱신
99697,2023,강남구,대치동,14.0,20230224,전세,128.03,100000,0,"쌍용대치아파트1동,2동,3동,5동,6동",1983.0,아파트,23.02~25.02,갱신
305902,2023,강남구,대치동,6.0,20230505,전세,84.43,70000,0,은마,1979.0,아파트,NaN,갱신
305903,2023,강남구,대치동,6.0,20230505,전세,84.43,70000,0,은마,1979.0,아파트,NaN,갱신
370424,2023,강남구,대치동,6.0,20230523,전세,84.89,52500,0,현대1,1990.0,아파트,23.06~25.06,갱신
370425,2023,강남구,대치동,6.0,20230523,전세,84.89,52500,0,현대1,1990.0,아파트,23.06~25.06,갱신
290218,2023,강남구,삼성동,25.0,20231127,월세,101.98,150000,310,래미안라클래시,2021.0,아파트,24.02~26.02,갱신
290220,2023,강남구,삼성동,25.0,20231127,월세,101.98,150000,310,래미안라클래시,2021.0,아파트,24.02~26.02,갱신
283889,2023,강남구,세곡동,1.0,20230527,월세,84.83,5000,220,세곡푸르지오,2012.0,아파트,23.06~24.06,갱신
283890,2023,강남구,세곡동,1.0,20230527,월세,84.83,5000,220,세곡푸르지오,2012.0,아파트,23.06~24.06,갱신
413445,2023,강남구,수서동,1.0,20231010,월세,34.44,1100,88,까치마을,1993.0,아파트,23.11~25.11,갱신
413466,2023,강남구,수서동,1.0,20231010,월세,34.44,1100,88,까치마을,1993.0,아파트,23.11~25.11,갱신
29371,2023,강남구,압구정동,10.0,20230113,전세,140.90,142000,0,미성2차,1987.0,아파트,NaN,갱신
29373,2023,강남구,압구정동,10.0,20230113,전세,140.90,142000,0,미성2차,1987.0,아파트,NaN,갱신
300971,2023,강동구,고덕동,12.0,20230511,월세,84.91,34000,45,아남1,1996.0,아파트,23.08~25.08,갱신
300972,2023,강동구,고덕동,12.0,20230511,월세,84.91,34000,45,아남1,1996.0,아파트,23.08~25.08,갱신

In [28]:
df_2023_full = pd.read_csv(file_2023)

df_2023_full.shape

(545813, 23)

In [29]:
df_apt_2023_full = df_2023_full[
    df_2023_full["건물용도"] == "아파트"
].copy()

df_apt_2023_full.shape

(233849, 23)

In [30]:
full_duplicate_count = df_apt_2023_full.duplicated().sum()

full_duplicate_count

np.int64(0)