In [21]:
from pathlib import Path
import pandas as pd

RAW_DIR = Path("../data/raw")

files = sorted(RAW_DIR.rglob("*.csv"))

for file in files:
    print(file.name)

서울특별시_전월세가_2023.csv
서울특별시_전월세가_2024.csv
서울특별시_전월세가_2025.csv

In [23]:
file_2023 = files[0]

df_sample = pd.read_csv(
    file_2023,
    nrows=5
)

df_sample

,접수년도,자치구코드,자치구명,법정동코드,법정동명,지번구분코드,지번구분,본번,부번,층,...,보증금(만원),임대료(만원),건물명,건축년도,건물용도,계약기간,신규계약구분,갱신청구권사용,종전보증금,종전임대료
0,2023,11440,마포구,11000,노고산동,1,대지,1,1,8,...,10000,40,\t(1-1)\t,1998,오피스텔,23.01~24.01,신규,NaN,0.0,0.0
1,2023,11440,마포구,11000,노고산동,1,대지,1,1,5,...,10000,55,\t(1-1)\t,1998,오피스텔,23.02~24.02,갱신,NaN,10000.0,55.0
2,2023,11440,마포구,11000,노고산동,1,대지,1,1,9,...,21000,0,\t(1-1)\t,1998,오피스텔,23.02~24.02,신규,NaN,0.0,NaN
3,2023,11170,용산구,11300,원효로2가,1,대지,1,0,9,...,23900,0,\t(1)\t,1990,오피스텔,23.09~25.09,신규,NaN,0.0,NaN
4,2023,11440,마포구,11000,노고산동,1,대지,1,1,9,...,22000,0,\t(1-1)\t,1998,오피스텔,NaN,NaN,NaN,NaN,NaN

In [24]:
df_sample.columns.tolist()

['접수년도',
 '자치구코드',
 '자치구명',
 '법정동코드',
 '법정동명',
 '지번구분코드',
 '지번구분',
 '본번',
 '부번',
 '층',
 '계약일',
 '전월세구분',
 '임대면적',
 '보증금(만원)',
 '임대료(만원)',
 '건물명',
 '건축년도',
 '건물용도',
 '계약기간',
 '신규계약구분',
 '갱신청구권사용',
 '종전보증금',
 '종전임대료']

In [25]:
len(df_sample.columns)

23

In [30]:
use_cols = [
    "접수년도",
    "자치구명",
    "법정동명",
    "층",
    "계약일",
    "전월세구분",
    "임대면적",
    "보증금(만원)",
    "임대료(만원)",
    "건물명",
    "건축년도",
    "건물용도",
    "계약기간",
    "신규계약구분",
]

df_2023 = pd.read_csv(
    file_2023,
    usecols=use_cols
)

df_2023.shape

(545813, 14)

In [27]:
df_2023["건물용도"].value_counts(dropna=False)

건물용도
아파트      233849
단독다가구    133456
연립다세대    116141
오피스텔      62367
Name: count, dtype: int64

In [28]:
df_2023["전월세구분"].value_counts(dropna=False)

전월세구분
월세    283341
전세    262472
Name: count, dtype: int64

In [29]:
df_2023["신규계약구분"].value_counts(dropna=False)

신규계약구분
신규     348168
갱신     106947
NaN     90698
Name: count, dtype: int64

In [31]:
df_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 545813 entries, 0 to 545812
Data columns (total 14 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   접수년도     545813 non-null  int64
 1   자치구명     545813 non-null  str
 2   법정동명     545813 non-null  str
 3   층        412357 non-null  float64
 4   계약일      545813 non-null  int64
 5   전월세구분    545813 non-null  str
 6   임대면적     545813 non-null  float64
 7   보증금(만원)  545813 non-null  int64
 8   임대료(만원)  545813 non-null  int64
 9   건물명      412357 non-null  str
 10  건축년도     536316 non-null  float64
 11  건물용도     545813 non-null  str
 12  계약기간     440065 non-null  str
 13  신규계약구분   455115 non-null  str
dtypes: float64(3), int64(4), str(7)
memory usage: 58.3 MB

In [32]:
df_apt_2023 = df_2023[
    df_2023["건물용도"] == "아파트"
].copy()

df_apt_2023.shape

(233849, 14)

In [33]:
df_apt_2023["전월세구분"].value_counts()

전월세구분
전세    139307
월세     94542
Name: count, dtype: int64

In [34]:
df_apt_2023["신규계약구분"].value_counts(dropna=False)

신규계약구분
신규     138033
갱신      61098
NaN     34718
Name: count, dtype: int64

In [35]:
df_apt_2023.isnull().sum().sort_values(ascending=False)

계약기간       51754
신규계약구분     34718
건축년도          47
법정동명           0
접수년도           0
자치구명           0
전월세구분          0
계약일            0
층              0
임대면적           0
건물명            0
임대료(만원)        0
보증금(만원)        0
건물용도           0
dtype: int64

In [36]:
df_apt_2023[
    [
        "층",
        "임대면적",
        "보증금(만원)",
        "임대료(만원)",
        "건축년도"
    ]
].describe()

,층,임대면적,보증금(만원),임대료(만원),건축년도
count,233849.000000,233849.000000,233849.000000,233849.000000,233802.000000
mean,9.520237,69.326181,38769.417932,40.962647,2004.467391
std,6.431148,28.653112,33200.254757,87.392642,12.450993
min,-2.000000,10.320000,0.000000,0.000000,1961.000000
25%,5.000000,51.120000,13347.000000,0.000000,1995.000000
50%,8.000000,59.990000,34000.000000,0.000000,2005.000000
75%,13.000000,84.920000,55000.000000,53.000000,2016.000000
max,69.000000,314.800000,740000.000000,4500.000000,2024.000000

In [37]:
df_apt_2023.dtypes

접수년도         int64
자치구명           str
법정동명           str
층          float64
계약일          int64
전월세구분          str
임대면적       float64
보증금(만원)      int64
임대료(만원)      int64
건물명            str
건축년도       float64
건물용도           str
계약기간           str
신규계약구분         str
dtype: object

In [38]:
df_apt_2023[
    [
        "층",
        "임대면적",
        "보증금(만원)",
        "임대료(만원)",
        "건축년도"
    ]
].describe()

,층,임대면적,보증금(만원),임대료(만원),건축년도
count,233849.000000,233849.000000,233849.000000,233849.000000,233802.000000
mean,9.520237,69.326181,38769.417932,40.962647,2004.467391
std,6.431148,28.653112,33200.254757,87.392642,12.450993
min,-2.000000,10.320000,0.000000,0.000000,1961.000000
25%,5.000000,51.120000,13347.000000,0.000000,1995.000000
50%,8.000000,59.990000,34000.000000,0.000000,2005.000000
75%,13.000000,84.920000,55000.000000,53.000000,2016.000000
max,69.000000,314.800000,740000.000000,4500.000000,2024.000000

In [39]:
print("면적 0 이하:",
      (df_apt_2023["임대면적"] <= 0).sum())

print("보증금 0 미만:",
      (df_apt_2023["보증금(만원)"] < 0).sum())

print("임대료 0 미만:",
      (df_apt_2023["임대료(만원)"] < 0).sum())

print("층 0 이하:",
      (df_apt_2023["층"] <= 0).sum())

print("건축년도 1900 미만:",
      (df_apt_2023["건축년도"] < 1900).sum())

면적 0 이하: 0
보증금 0 미만: 0
임대료 0 미만: 0
층 0 이하: 23
건축년도 1900 미만: 0

In [40]:
df_apt_2023.duplicated().sum()

np.int64(103)

In [41]:
print(
    "전세인데 월세가 0이 아닌 건수:",
    (
        (df_apt_2023["전월세구분"] == "전세")
        & (df_apt_2023["임대료(만원)"] != 0)
    ).sum()
)

print(
    "월세인데 월세가 0인 건수:",
    (
        (df_apt_2023["전월세구분"] == "월세")
        & (df_apt_2023["임대료(만원)"] == 0)
    ).sum()
)

전세인데 월세가 0이 아닌 건수: 0
월세인데 월세가 0인 건수: 35